### ISSUE TITLE
Build Failed in Release Mode (ios)

### ISSUE THREAD

**Issue by gkmuhannad** [OpenFlutter/flutter_share_me#48] opened 2021-08-16 11:06 UTC
Hello,
I tried to build a release version but I got this error, it works in debug mode.

Undefined symbols for architecture arm64:
"OBJC_CLASS$_FBSDKShareLinkContent", referenced from:
objc-class-ref in SwiftFlutterShareMePlugin.o
"OBJC_CLASS$_FBSDKShareDialog", referenced from:
objc-class-ref in SwiftFlutterShareMePlugin.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Analyzing workspace
note: Constructing build description
note: Build preparation complete

**Comment by gkmuhannad** [comment] 2021-08-19 08:47
kindly reminder
@jigarfumakiya

**Comment by jigarfumakiya** [comment] 2021-08-19 09:27
@gkmuhannad 
I Will debug later today but I think that is not a plugin issue.
Can you tell me which swift version and ios platform version you are using?

**Comment by gkmuhannad** [comment] 2021-08-19 09:30
thanks a lot

Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
Target: x86_64-apple-darwin20.6.0

This ios platform version : 14.4

**Comment by gkmuhannad** [comment] 2021-08-25 12:17
is there any update ?

**Comment by gkmuhannad** [comment] 2021-08-30 14:06
the problem still not solved in the new version

**Comment by megataps** [comment] 2021-08-30 14:37
I got the same problem. Please help to fix

**Comment by jigarfumakiya** [comment] 2021-08-31 05:19
@gkmuhannad  Sorry for the delay.
 I am not able to reproduce the issue I have uploaded the build to test flight it's working fine.
 Can you set ios platform version: 10 and the same swift version.
do Flutter clean
and Try again.

**Comment by gkmuhannad** [comment] 2021-08-31 09:43
Hello @jigarfumakiya 

What swift version are you use? 
and take a look please for the screenshot

![Screen Shot 1443-01-23 at 12 40 45 PM](https://user-images.githubusercontent.com/80851543/131480403-e0efde9c-6d59-452a-a9d9-3358199fec2f.png)


Thanks for helping us.

**Comment by jigarfumakiya** [comment] 2021-08-31 09:46
@gkmuhannad Ohh. ok by any chance you working with m1 mac.?
Please clear derived data in code and then do flutter clean and run from android studio

**Comment by gkmuhannad** [comment] 2021-08-31 09:51
@jigarfumakiya 
no I am woking with Mac book retina 2013
ok I will do it and let you know

**Comment by jigarfumakiya** [comment] 2021-08-31 09:53
Sure delete pods file and pods folder as well.

**Comment by gkmuhannad** [comment] 2021-08-31 10:06
@jigarfumakiya 
I did all steps:
- flutter clean
- clear derived data
- delete podfile & pods folder


but still the same problem, that is so weird ☹️
I really need this package it is very useful

**Comment by jigarfumakiya** [comment] 2021-08-31 10:51
@gkmuhannad Please upload a sample and share link and will check later.

**Comment by gkmuhannad** [comment] 2021-08-31 11:08
@jigarfumakiya
sample of what ?
my project is very large and already it is a live in the stores Apple & Google
but I need to update the sharing method in the project

**Comment by jigarfumakiya** [comment] 2021-09-01 10:03
Hey @gkmuhannad @megataps 
Can you try this, please 

```
flutter_share_me:
    git:
        url: https://github.com/OpenFlutter/flutter_share_me.git
        ref: v2.0.0
```

Make sure you do 

- Delete pods folder, pod file, and pod. lock file.
- Delete pubspec.lock .
- Flutter clean.


Let me know the result

**Comment by gkmuhannad** [comment] 2021-09-01 10:39
Hello @jigarfumakiya 
Thank you so much for your support.

It works now 😍

**Comment by jigarfumakiya** [comment] 2021-09-01 10:43
Perfect 👍

**Comment by megataps** [comment] 2021-09-01 14:15
It worked! Thanks @jigarfumakiya  and @gkmuhannad

**Comment by jigarfumakiya** [comment] 2021-09-02 04:45
Closing the issue.
Feel free to open new if you have any issues.

**Closed by jigarfumakiya** 2021-09-02 04:45 UTC
Labels: bug
